// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alliance struct {
	Name          *string
	Tag           string
	AllianceID    string
	Region        string
	SkipNameCheck bool
	FirstSeen     time.Time
	LastSeen      time.Time
}

type Guild struct {
	Name      string
	GuildID   string
	Region    string
	FirstSeen time.Time
	LastSeen  time.Time
}

type GuildAllianceMembership struct {
	ID         pgtype.UUID
	GuildID    string
	AllianceID string
	Region     string
	IsActive   bool
	FirstSeen  time.Time
	LastSeen   time.Time
}

type Player struct {
	Name      string
	PlayerID  string
	Region    string
	FirstSeen time.Time
	LastSeen  time.Time
}

type PlayerGuildMembership struct {
	ID        pgtype.UUID
	PlayerID  string
	GuildID   string
	Region    string
	IsActive  bool
	FirstSeen time.Time
	LastSeen  time.Time
}
